# Generated by Django 5.0.2 on 2024-05-31 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_airport_city_airport_country_airport_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_5m', models.FloatField()),
                ('temperature_120m', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.airport')),
            ],
        ),
    ]
