# Generated by Django 5.0.6 on 2024-06-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_weatherdata_temperature_120m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='snow_depth',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='snowfall',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_speed_10m',
            field=models.JSONField(default=dict),
        ),
    ]
